"""add_unique_constraint_to_notifications

Revision ID: 73212fca90b8
Revises: 76a1490ff5ee
Create Date: 2026-06-24 23:58:41.947126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73212fca90b8'
down_revision: Union[str, Sequence[str], None] = '76a1490ff5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_title_msg_uc', ['user_id', 'title', 'message'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('_user_title_msg_uc', type_='unique')
    # ### end Alembic commands ###
