"""migrate_date_columns_to_date_type

Revision ID: 76a1490ff5ee
Revises: 935328bdf1c7
Create Date: 2026-06-24 23:04:00.547049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a1490ff5ee'
down_revision: Union[str, Sequence[str], None] = '935328bdf1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys = OFF")
    with op.batch_alter_table('milestones') as batch_op:
        batch_op.alter_column('exam_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True)
    with op.batch_alter_table('resources') as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)
    with op.batch_alter_table('study_sessions') as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
    op.execute("PRAGMA foreign_keys = ON")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys = OFF")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    with op.batch_alter_table('study_sessions') as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    with op.batch_alter_table('resources') as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)
    with op.batch_alter_table('milestones') as batch_op:
        batch_op.alter_column('exam_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.execute("PRAGMA foreign_keys = ON")
    # ### end Alembic commands ###
