"""add_exam_time_to_milestones

Revision ID: e5f86a563b66
Revises: 4d1897c7bded
Create Date: 2026-07-03 02:02:19.682337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f86a563b66'
down_revision: Union[str, Sequence[str], None] = '4d1897c7bded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('exam_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'exam_time')
    # ### end Alembic commands ###
