"""add_check_constraints_to_tasks_and_subjects

Revision ID: f167df234b21
Revises: 73212fca90b8
Create Date: 2026-06-25 00:03:29.150025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f167df234b21'
down_revision: Union[str, Sequence[str], None] = '73212fca90b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
